### ISSUE TITLE
Logically error in calling obsoleted function getAge

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/module-alumni#4]
There is a use of the getAge function in [publicRegistrationProcess.php](https://github.com/GibbonEdu/module-alumni/blob/b15fa9973463870511018dae98f5cbb8e6d559ce/Alumni/publicRegistrationProcess.php#L72) that depends on:
1. Function's first parameter is `$guid`, which is an old function signature; and
2. [`getAge`](https://github.com/GibbonEdu/core/blob/beedf7eb7171b6be3e9c81bfdcc085f87397b113/functions.php#L3322-L3328) supports the parameter `$yearsOnly`, which is no longer true after GibbonEdu/core@ec5ae0a77e.

If the code I referenced is actually called, it should not be working as expected at all.

Potential fix:
1. Add the `$yearsOnly` to [`Format::age`](https://github.com/GibbonEdu/core/blob/beedf7eb7171b6be3e9c81bfdcc085f87397b113/src/Services/Format.php#L297-L314) then use it directly.
2. Add the `$yearsOnly` to [`Format::age`](https://github.com/GibbonEdu/core/blob/beedf7eb7171b6be3e9c81bfdcc085f87397b113/src/Services/Format.php#L297-L314) then use it through updated `getAge` function, which is deprecated in v16.
3. Add a new method in class [`Format`](https://github.com/GibbonEdu/core/blob/beedf7eb7171b6be3e9c81bfdcc085f87397b113/src/Services/Format.php), then use it to calculate specifically the year difference.
4. Rewrite this specifically within the module to remove all dependencies from core.

**Comment by rossdotparker** [comment]
I see that removing getAge() seems to be the preferred route. I'll merge those PRs shortly, and hopefully that does the trick. Thanks!

**Comment by yookoala** [comment]
It's just much easier, especially when I only found 2 use case of `$yearOnly` in the entire code base (includes both core and open source modules).
